// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIyoM7ASKWvXdLD_mAZkmeTG9ybQP91Q',
    appId: '1:880598798157:web:0a00c7660bef59438ff104',
    messagingSenderId: '880598798157',
    projectId: 'medg-7656c',
    authDomain: 'medg-7656c.firebaseapp.com',
    storageBucket: 'medg-7656c.appspot.com',
    measurementId: 'G-QLS4W5HW9X',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR1rnCYxRgicp9BS7xdMk8I3ASQpkH8B8',
    appId: '1:880598798157:android:92b9f6e680a89e3e8ff104',
    messagingSenderId: '880598798157',
    projectId: 'medg-7656c',
    storageBucket: 'medg-7656c.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyComA961ILkJDXSx0oTpx_gfGB8NXintBg',
    appId: '1:880598798157:ios:fa502de1bf72886b8ff104',
    messagingSenderId: '880598798157',
    projectId: 'medg-7656c',
    storageBucket: 'medg-7656c.appspot.com',
    iosBundleId: 'com.example.medg',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyComA961ILkJDXSx0oTpx_gfGB8NXintBg',
    appId: '1:880598798157:ios:591f41b7e61b3a798ff104',
    messagingSenderId: '880598798157',
    projectId: 'medg-7656c',
    storageBucket: 'medg-7656c.appspot.com',
    iosBundleId: 'com.example.medg.RunnerTests',
  );
}
